version: 2
jobs:
  build:
    branches:
      only: main

    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo

    steps:
      - filters:
          branches:
            only:
              - main

      - checkout
      - run:
          name: install dependencies
          command: |
            pip3 install -r requirements.txt

      - run:
          name: run tests
          command: |
            flake8 --exclude=env* --statistics
            pytest -v